### ISSUE TITLE
What is ignored DynamicWorld value?

### ISSUE THREAD

**Issue by kvantricht** [nasaharvest/presto#23]
Sorry for the many questions, but again a bit confused here.

when using `presto.construct_single_presto_input` without DynamicWorld, the returned `dynamic_world` has fixed values of `9`. As per the ReadMe, it should be `10`:

> dynamic_world: torch.Tensor of shape [batch_size, num_timesteps]. If no Dynamic World classes are available, this tensor should be filled with the value [DynamicWorld2020_2021.class_amount + 1](https://github.com/nasaharvest/presto/blob/main/presto/dataops/pipelines/dynamicworld.py) (i.e. 10), in which case it is ignored.

If I manually try to feed a fixed tensor of value `10` to Presto, I get `IndexError: index out of range in self`, while with a value of `9` it works. Could you clarify what we're supposed to do in absence of DynamicWorld?

**Comment by gabrieltseng** [comment]
No need to apologize; thank you so much for testing out the code (and apologies on my behalf for the parts where its not clear). 

This is a typo in the README - as is done [elsewhere in the codebase](https://github.com/nasaharvest/presto/blob/445d7ca212c8bc03ea25c5c9713701b1bdc1cbc9/presto/eval/eval.py#L414), missing Dynamic World values have a value of `9` (so `DynamicWorld2020_2021.class_amount`, without the `+1`). This is because we index from `0` with `9` Dynamic World classes (`0-8`).
